### ISSUE TITLE
Feedback for /docs/quarks/quarks-getting-started/

### ISSUE THREAD

**Issue by chanskw** [quarks-edge/quarks.documentation#10]
Formatting seems to be messed up here:

Adding the console to your application

DevelopmentTopologyProvider dtp = new DevelopmentTopologyProvider(); Topology t = dtp.newTopology(“MyTopology”); // add oplets to the topology … // submit the topology dtp.submit(t, Collections.emptyMap());

// make a call to getServices, get the HttpServer service, // and call getConsoleUrl() which returns the url the // console is available at System.out.println(dtp.getServices().getService(HttpServer.class).getConsoleUrl());

**Comment by ddebrunner** [comment]
Also see #2  which requests the console topic be moved into a new page.

**Comment by ddebrunner** [comment]
"add oplets to the topology"

should be replaced with "build your application's topology

**Comment by dlaboss** [comment]
It's `DevelopmentProvider`, no longer `DevelopmentTopologyProvider`.  
submit() no longer takes a 2nd argument (remove the map).

**Comment by kathyssaunders** [comment]
Resolved with https://github.com/quarks-edge/quarks.documentation/pull/20
