### ISSUE TITLE
Feedback for /docs/quarks/quarks-getting-started/

### ISSUE THREAD

**Issue by mnwone** [quarks-edge/quarks.documentation#12]
Suggestion: add definitions (or links to definitions) for oplet and stream tag and somewhere explain the relationship between TStream method calls and oplets.

Minor editorial comments:
- You you > You
- Make section heading capitalization convention more consistent. For example, the first character of all  words in 'Defining The Objects' are capitalized but in other headings the first letter may be upper or lower case
- 3 '*' - are each these items intended to be indented and formatted in a list?
- In 'Accessing the console', format code snippet in a gray box
- send tuples to an MQTT > send tuples to a MQTT
- I've been able to access the console running a browser running on a machine that is different from where the Quarks application is running by replacing localhost with the host IP -this is the beauty of a web app.

**Comment by juliabamford** [comment]
@mnwone There are a few comments that I am unable to respond to:
- 3 '*' - are each these items intended to be indented and formatted in a list? 
   I'm not sure what this is referring to.
- Looks like the "Accessing the console" snippet is already in a gray box in the console topic. 
- send tuples to an MQTT > send tuples to a MQTT
   I'm going to leave this as-is. General consensus is that the indefinite article (a vs an) is determined by the sound of the acronym, not the letter and not the word that the first letter of the acronym represents.

**Comment by ddebrunner** [comment]
> add definitions (or links to definitions) for oplet and stream tag and somewhere explain the relationship between TStream method calls and oplets.

The getting started guide does not mention oplets, so it's unclear why a reference would need to be added.

Since it's a "getting started" it was intentionally simple and focussed on the high-level topology api where oplets are not relevant. The idea was to have follow on articles that explain in more detail. "less is more" for a getting started guide.

**Comment by mnwone** [comment]
It looks like the original page's contents was moved to multiple pages.

@juliabamford - these are fixed now.

@ddebruner -  I agree 'getting started' should be simple. 
I believe early on, many sections were on 1 page. Now the oplet reference got moved to http://quarks-edge.github.io/quarks.documentation/docs/quarks/console/, so the comment applies to this page now.

**Comment by juliabamford** [comment]
@mnwone I'm going to create a separate issue to tackle the issue of how to discuss concepts. Per your comment above (add definitions (or links to definitions) for oplet and stream tag and somewhere explain the relationship between TStream method calls and oplets.)
