### ISSUE TITLE
Feedback for /docs/quarks/samples/iotf/quickstart/

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks.documentation#18]
I just added this page and had it embed some images in the sub-folder images but they are not displayed. I assume it's because the path is not where I thought it would be.

Maybe it's something to do with how the .md pages are remapped, e.g. quickstart.md is at the URL .../quickstart (no .md).

Anyone know what the correct image path would be?

**Comment by ddebrunner** [comment]
The link is:

http://quarks-edge.github.io/quarks.documentation//docs/quarks/samples/iotf/quickstart/

**Comment by chanskw** [comment]
When Jekyll generates the pages, it will create a _site folder.

Under there, your documentation is generated in:
_site/docs/quarks/samples/iotf/quickstart/index.html

The images are located at:
_site/doc/quarks/samples/iotf/quickstart/images/

I believe you have to do something like this:
`<img border="0" alt="Quickstart sample output" src="../images/Quickstart_device.png">`

Please try and see if it works?

**Comment by ddebrunner** [comment]
Thanks, that fixed it!

Kind of strange that it was working when viewed as a file but not as the website, and now it's the opposite. :-)
