### ISSUE TITLE
Create a instructions on how to contribute documentation to Quarks

### ISSUE THREAD

**Issue by kathyssaunders** [quarks-edge/quarks.documentation#24]
We should have instructions on what to do if you want to contribute documentation to Quarks.  I would love to see people continuing to improve and add to the documentation, and found that it took me a while to figure it all out.  I hope instructions like this will help others.

**Comment by kathyssaunders** [comment]
Started a wiki page at https://github.com/quarks-edge/quarks.documentation/wiki/Contributing-Documentation which is still in process.

**Comment by ddebrunner** [comment]
Good idea, the info is this issue #18 is useful as it wasn't clear to me how the source files (.md) map to paths in the generate site.

**Comment by kathyssaunders** [comment]
I finished creating the wiki page at  https://github.com/quarks-edge/quarks.documentation/wiki/Contributing-Documentation.  Please try it out and post any comments here or make edits directly.
