### ISSUE TITLE
Quarks Redbook?

### ISSUE THREAD

**Issue by jms90h5** [quarks-edge/quarks.documentation#28]
The first three Redbooks were important educational resources for the InfoSphere Streams product.  I think one would be at least as useful for Quarks. And probably relatively easy to produce since some of the content for the Streams Java API might be able to be repurposed.

**Comment by kathyssaunders** [comment]
Thank you for the comment.  I suggest you take that request back to IBM since Redbooks are an IBM initiative which we won't be able to address here.  Since I work for IBM, I will also send your feedback to IBM.

**Comment by ddebrunner** [comment]
Also see issue #16
