### ISSUE TITLE
Create link to quickstart sample

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks.documentation#32]
In pull request #23 I tried to add a link to this page but I couldn't figure out the correct relative path.

http://quarks-edge.github.io/quarks.documentation/docs/quarks/samples/iotf/quickstart/

**Comment by Alex-Cook4** [comment]
I believe the relative paths are done relative to the project base starting with "/quarks.documentation/".

So for your case, the path should be: "/quarks.documentation/docs/quarks/samples/iotf/quickstart/"

**Comment by ddebrunner** [comment]
Thanks @Alex-Cook4 I created a pull request with that path.
