### ISSUE TITLE
New to Quark

### ISSUE THREAD

**Issue by manjunath-maha** [quarks-edge/quarks.documentation#36]
Hi,
I am new to Quark. please send me the Documentation on Quark
Thanks
Manju

**Comment by chanskw** [comment]
Here's our main website:  http://quarks-edge.github.io
Here's our documentation site:  http://quarks-edge.github.io/quarks.documentation/

**Comment by manjunath-maha** [comment]
Hi samatha,

I am referring the Documentation you have indicated in your main.
But See the following in the page about New documentation.

Quote:
New Documentation

To request new documentation, please open an issue he

Unquote:

Is there any New Documentation? If so please send the link.

Thanks

Manju

Manjunath Mahashetti
CEO
www.ineosoft.in
http://in.linkedin.com/in/manjunathmahashetti+919886725346
- in.linkedin.com/in/manjunathmahashetti/

http://in.linkedin.com/in/manjunathmahashettiLet us protect our only home
- The Earth, we have no where else to go.

**Comment by mikespicer** [comment]
@manjunath-maha "To request new documentation, please open an issue" means that if you have find that there are subjects that are not covered in the documentation you can open an issue to request that documentation be added to cover that subject.  All of the current documentation is in github and available for you to see and also for you to contribute to as you learn more and see areas that you can help improve.

**Comment by manjunath-maha** [comment]
Thanks Mike!
