### ISSUE TITLE
Feedback for /

### ISSUE THREAD

**Issue by chanskw** [quarks-edge/quarks.documentation#37]
From the main documentation page, or the banner, we should have a link back to there:
http://quarks-edge.github.io

The links at the top seem to point to the same places:
Home - main documentation page
Github - Documentation project in Github
Documentation - main documentation page
Project - Documentation project in Github

It seem a bit odd that we have duplicated links like this.

**Comment by kathyssaunders** [comment]
Closing this since the web site is now at Apache and has been changed.
