### ISSUE TITLE
Feedback for /

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks.documentation#4]
At the top under "Quarks Documentation" it says:

Documentation for Quarks Project

Which is not very helpful, seems like a brief overview of what Quarks is would be useful here.

**Comment by kathyssaunders** [comment]
Added changes to http://quarks-edge.github.io/quarks.documentation/index.html similar to the readme.  https://github.com/quarks-edge/quarks.documentation/pull/22
