### ISSUE TITLE
Update the Application console page with a detailed example

### ISSUE THREAD

**Issue by home4slc** [quarks-edge/quarks.documentation#41]
I'm going to add content to this page:
http://quarks-edge.github.io/quarks.documentation/docs/quarks/console/

using the ConsoleWaterDetector sample application as a guide.  I'll point out the features of the console and how to use them to explore and better understand an application.

**Comment by home4slc** [comment]
I can add the content using markdown, but would appreciate the help getting it into the docs once it is ready.

**Comment by kathyssaunders** [comment]
I can get it into the docs once you post the markdown.  Thanks for contributing to the docs.

**Comment by home4slc** [comment]
I'm trying to get git set up properly so I can modify console.md.  Here is what I have done so far, and the problem I am having:
1. Forked quarks-edge/quarks.documentation
2. Cloned it: git clone https://github.com/home4slc/quarks.documentation.git
3. Added a new remote:
   git remote add gh-pages https://github.com/quarks-edge/quarks.documentation.git
4. git checkout gh-pages
5. git fetch upstream <-- a problem, here is the error I got:
   quarks.documentation susancline$ git fetch upstream
   fatal: 'upstream' does not appear to be a git repository
   fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Do I have to do a 'git fetch gh-pages' ?

Thanks!

**Comment by kathyssaunders** [comment]
Susan and I looked at her git problem by comparing 'git remote -v' in both of our environments.  We found she had made an error in her 'git remote add'.  The command that worked was 'git remote add upstream https://github.com/quarks-edge/quarks.documentation.git'. Once she corrected that, all seemed to be working fine.

**Comment by home4slc** [comment]
Attached is an updated console.md and many images that are screen shots of the console that go in the page.  I viewed them in a markdown extension on chrome, but I can't guarantee every thing looks correct.  @kathyssaunders would you mind telling me if anything is wrong when you try it out?  I can fix them if there is.  Thanks!

![console_counter_metrics_bar](https://cloud.githubusercontent.com/assets/17278663/13582884/8988a0b4-e463-11e5-8560-c74cc45c9c38.jpg)
![console_hover_over_link](https://cloud.githubusercontent.com/assets/17278663/13582882/8985d23a-e463-11e5-8949-0a56ec4d9eca.jpg)
![console_hover_over_op](https://cloud.githubusercontent.com/assets/17278663/13582883/8986285c-e463-11e5-9ac9-102e1d71946a.jpg)
![console_metrics_line_chart](https://cloud.githubusercontent.com/assets/17278663/13582885/89896580-e463-11e5-9d9f-7bc2ce2fa002.jpg)
![console_oplet_kind](https://cloud.githubusercontent.com/assets/17278663/13582881/89855e4a-e463-11e5-9966-4f218614feae.jpg)
![console_oplet_properties](https://cloud.githubusercontent.com/assets/17278663/13582880/8982e0e8-e463-11e5-88ea-0eaee63fc45f.jpg)
![console_overview](https://cloud.githubusercontent.com/assets/17278663/13582886/89978f0c-e463-11e5-969b-b7fd61a07a97.jpg)
![console_rate_metrics](https://cloud.githubusercontent.com/assets/17278663/13582888/899a689e-e463-11e5-9a6a-3e5664271798.jpg)
![console_select_individual_tags](https://cloud.githubusercontent.com/assets/17278663/13582887/899a4f62-e463-11e5-9c9a-998d89d3e1d4.jpg)
![console_stream_tags_legend](https://cloud.githubusercontent.com/assets/17278663/13582891/899e5f80-e463-11e5-8c03-c688e7693f9a.jpg)
![console_top_controls](https://cloud.githubusercontent.com/assets/17278663/13582889/899aefa8-e463-11e5-92ca-973bc313b64c.jpg)
![console_tuple_count](https://cloud.githubusercontent.com/assets/17278663/13582890/899c3afc-e463-11e5-9fbf-600df0442ed5.jpg)

**Comment by kathyssaunders** [comment]
I will try this out soon.

Kathy

**Comment by kathyssaunders** [comment]
@home4slc, did you attach the .md file?

**Comment by home4slc** [comment]
I thought I did, but I sure don't see it!  Sorry about that.  Ah, oddly enough when I try it says that it does not support 'that type of file'.  The *.md file.  How about I rename it and attach it as a .txt .. here we go.
[console.txt](https://github.com/quarks-edge/quarks.documentation/files/163448/console.txt)

**Comment by kathyssaunders** [comment]
Last night I worked on this and my current version is at https://github.com/kathyssaunders/quarks.documentation/blob/kathy-branch/mydoc/console.md.  I did some editing, fixed a couple of formatting issues, and took a stab at adding in some of the images.  The images attached here seem to have lost their names, so I did my best to put them in the right place, and I didn't get them all in.  If this can be reviewed and label the remaining images with their correct names, I can get another version going.  Once it's been reviewed, I can create a pull request from my branch if that makes sense.

**Comment by home4slc** [comment]
Here is a zip file of all the images, please let me know if this helps or you need me to correlate stuff.
Thanks!
[console_images.zip](https://github.com/quarks-edge/quarks.documentation/files/165730/console_images.zip)

**Comment by kathyssaunders** [comment]
The zip file helped a lot.  I got all of the images uploaded, and anyone can review at https://github.com/kathyssaunders/quarks.documentation/blob/kathy-branch/mydoc/console.md.  Let me know if it looks ok. I can create a pull request and merge since this is all in my branch unless someone else wants to do it.  I'm not sure when the doc repository is going to be moved to Apache, but it would be good to merge this before that happens.

**Comment by home4slc** [comment]
Thanks for your help.  All the images look correct.

**Comment by home4slc** [comment]
If someone wants to do the pull request, that would be great!

**Comment by kathyssaunders** [comment]
Merged using https://github.com/quarks-edge/quarks.documentation/pull/58.  The new console write-up and associated images are available as part of the documentation.
