### ISSUE TITLE
EtiaoJob  multiple id and name methods.

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks.documentation#50]
getId() and getJobId()

getName() and getJobName()

I would have expected only a getId() and getName().

**Comment by ddebrunner** [comment]
Looking more closely, maybe it's ok, but maybe some javadoc would help.

**Comment by vdogaru** [comment]
Methods belong to the Job and JobContext interfaces. I assume that, prior to introducing JobContext,  getJobId used to belong to the OpletContext interface and the "job" qualifier would distinguish it from the OpletContext.getId() method.

I think changing the names to JobContext.getId() and JobContext.getName() is good, it would make the interfaces more clear. It's confusing that the same class implements both interfaces, I'll look into changing that, maybe have an inner class (to EtiaoJob) implement JobContext.

**Comment by ddebrunner** [comment]
Why would an inner class be needed?

**Comment by vdogaru** [comment]
On a second look, an inner class is not needed.  I just renamed JobContext.getJobId() and JobContext.getJobName() to getId() and getName(), respectively.
