### ISSUE TITLE
Warning building the documentation

### ISSUE THREAD

**Issue by kathyssaunders** [quarks-edge/quarks.documentation#57]
I have been updating the documentation on my branch and the following email was sent.  I believe the page that triggered this message is https://github.com/kathyssaunders/quarks.documentation/blob/kathy-branch/mydoc/console.md.  I will try to look into this, but if anyone knows about this warning or thinks we should change the pygments highlighter as the message states, please post to this issue.

The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by home4slc** [comment]
Hum, sorry to cause trouble .  I edited that page using Atom but did not install Jekyll.  If you figure out the cause, and now how to fix it I can redo the page.

**Comment by kathyssaunders** [comment]
Closing issue since the documentation has moved to Apache
